### ISSUE TITLE
Works with ESP32-c3?

### ISSUE THREAD

**Issue by lucasmontec-fortis** [schnoog/Joystick_ESP32S2#11]
Have you tested with small form factor ESP32 like the c3?

**Comment by schnoog** [comment]
Hi, not tested the C3 since I only have a couple of S2 and S3 laying around. 

Based on the information I found, the USB implementation in the C3 only allows Serial and JTAG but not to create HID devices like Mouse and Joystick. If that's correct the library will not work.
If you already have a C3 I would appreciate if you could test it.

If only the form factor is crucial to you, you can also opt for a S3 with a similar form factor (like f.e. the Waveshare ESP32-S3 Mini)
